general:
  database:
    name: 'db.db'
    path: 'database/'
  proxy:
    active: False
    ip: "0.0.0.0"
    port: 50
  emails:
    smtp: "0.0.0.0"
    sender: "sender@email.com"
    port: 25

cve:
  email:
    active: False
    to:
      - "to@to.com"
    template: "config/template.html"
  telegram:
    active: True
    token: "TOKEN"
    chat: "CHAT"
    template: "config/telegram.md"
  vendor:
    active: True
  type: "Vulnerability"
  app: "NVD"
  mitre: None
  landscape:
    - "Vulnerability"
    - "CVE"
  score: 7.5
  lastdays: 1
  urls:
    - "https://services.nvd.nist.gov/rest/json/cves/1.0?modStartDate="
    - "https://services.nvd.nist.gov/rest/json/cves/1.0?pubStartDate="
    - "https://services.nvd.nist.gov/rest/json/cves/1.0?startIndex=100&resultsPerPage=100"
  products:
    - "windows"
    - "microsoft"
    - "oracle"
    - "mcafee"
    - "sap"
    - "debian"
    - "fedoraproject"
    - "redhat"
    - "ubuntu"
    - "3com"
    - "alcatel"
    - "brocade"
    - "cisco"
    - "cyclades"
    - "datacom"
    - "extreme"
    - "f5"
    - "hp"
    - "huawei"
    - "juniper"
    - "marconi"
    - "unix"
    - "zabbix"
    - "vmware"
    - "jetbeans"
    - 'firefox'
    - 'google'
    - 'chrome'
    - 'jenkins'
    - 'apple'
    - 'adobe'
    - 'android'
    - 'bind'
    - 'cisco'
    - 'dell'
    - 'dedecms'
    - 'd_link'
    - 'f5'
    - 'freebsd'
    - 'fireeye'
    - 'firefox'
    - 'fortinet'
    - 'hpe'
    - 'huawei'
    - 'ibm'
    - 'ibm_websphere'
    - 'icewarp'
    - 'intel'
    - 'internet_explorer'
    - 'k9mail'
    - 'keepass'
    - 'kibana'
    - 'kubernetes'
    - 'lantech'
    - 'linux'
    - 'manageengine'
    - 'mcafee'
    - 'microsoft'
    - 'mikrotik'
    - 'moxa'
    - 'myadmin'
    - 'mysql'
    - 'nikto'
    - 'nvidia'
    - 'opmanager'
    - 'oracle'
    - 'oracle_goldengate'
    - 'palo_alto_expedition'
    - 'perl'
    - 'philips'
    - 'php'
    - 'ricoh'
    - 'rockwell'
    - 'sap'
    - 'solaris'
    - 'schneider'
    - 'sierra_wireless'
    - 'splunk'
    - 'tenable'
    - 'wordpress'
    - 'nuix'
    - 'opentext'
    - 'trend_micro'
    - 'hp'
    - 'sevenzip'
    - 'apache'
    - 'autodesk'
    - 'certsign'
    - 'citrix'
    - 'lotus'
    - 'mozilla'
    - 'knoa'
    - 'pdfforge'
    - 'pulsesecure'
    - 'sophos'
    - 'symantec'
    - 'videolan'
    - 'redhat'
    - 'bluecoat'
    - 'juniper'
    - 'palo_alto'
    - 'django'
    - 'lumis'
    - 'drupal'
    - 'php'
    - 'siemens'
    - 'honeywell'
    - 'eclipse'
    - 'jetbrains'
    - 'mariadb'
    - 'fluke'
    - 'osisoft'
